version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: backend
    env_file: .env
    ports:
      - '3000:3000'
    command: npm run dev
